--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=game:GetService("ReplicatedStorage");local v1=game:GetService("Players");local v2=v1.LocalPlayer;local v3=v2:WaitForChild("Backpack");local v4=v2.Character or v2.CharacterAdded:Wait() ;local v5=v4:WaitForChild("Humanoid");local v6=v0:WaitForChild("PoopChargeStart");local v7=v0:WaitForChild("PoopEvent");local v8=v0:WaitForChild("PoopResponseChosen");local v9=loadstring(game:HttpGet("https://raw.githubusercontent.com/4lpaca-pin/CompKiller/refs/heads/main/src/source.luau"))();local v10=v9.new({Name="Auto Pooper",Keybind="LeftAlt",Logo="rbxassetid://109700863387451",Scale=v9.Scale.Window,TextSize=946 -(857 + 74) });local v11=v10:DrawTab({Name="Pooper",Icon="poo",EnableScrolling=false});local v12=v11:DrawSection({Name="Main",Position="left"});local v13=0.08;local v14=568.08 -(367 + 201) ;local v15=false;local v16=false;local function v17() while v15 do pcall(function() v6:FireServer();task.wait(v14);v7:FireServer(1);end);task.wait(v13);end end local function v18() while v16 do v8:FireServer("2. [I want to sell my inventory.]");task.wait(929.2 -(214 + 713) );end end local function v19() local v20=0 + 0 ;local v21;local v22;while true do if (v20==1) then for v26,v27 in ipairs(v3:GetChildren()) do if v27:IsA("Tool") then local v28=0 + 0 ;local v29;while true do if (v28==(877 -(282 + 595))) then v29=v27.Name:match("%((%d+%.?%d*) lbs%)");if v29 then local v30=tonumber(v29);if (v30 and (v30>v22)) then local v31=1637 -(1523 + 114) ;while true do if (v31==(0 + 0)) then v22=v30;v21=v27;break;end end end end break;end end end end if v21 then v5:EquipTool(v21);end break;end if (v20==(0 -0)) then v21=nil;v22= -(1066 -(68 + 997));v20=1271 -(226 + 1044) ;end end end v12:AddToggle({Name="Auto Poop Fast",Flag="Auto_Poop_Toggle",Default=false,Callback=function(v23) v15=v23;if v23 then task.spawn(v17);end end});v12:AddButton({Name="Equip Heaviest Poop",Callback=v19});v12:AddToggle({Name="Auto Sell All",Flag="Auto_Sell_Toggle",Default=false,Callback=function(v24) local v25=0 -0 ;while true do if (v25==0) then v16=v24;if v24 then task.spawn(v18);end break;end end end});
